#!/usr/bin/python3

import network
import pickle
import load_data

if __name__ == "__main__":
    nw = network.Network()
    model = "model/1.model.pkl"
    f = open(model, "rb")
    nw.bias = pickle.load(f)
    nw.weight = pickle.load(f)
    nw.sizes = pickle.load(f)
    ta_data, va_data, te_data = load_data.load_data_wrapper()
    correct = nw.evaluate(list(te_data))
    print("res: %d / %d", correct, len(list(te_data)))
